### ISSUE TITLE
Using quite outdated version of p5js

### ISSUE THREAD

**Issue by steezeburger** [makinteract/p5js-wrapper#2]
Have you added any code around p5js or is `index.js` simply the unminified p5js code? I am not so familiar with it.

I think it would be great if we could get this updated though! Then your other project p5js-vite would be using the latest version of p5js :)

**Comment by makinteract** [comment]
You have a good point. In the upcoming week, I will try to take a look at a better way to get the latest version and keep it updated without manual intervention. Thanks for the feedback!

**Comment by makinteract** [comment]
Thanks again for your suggestion. I have modified the code so that it wraps directly the official [p5](https://www.npmjs.com/package/p5) package on npm (using the latest version). The difference with the prior version is that now you need to use _named imports_ like `import {sketch} from 'p5js-wrapper'` for single-sketch apps, and `import {p5} from 'p5js-wrapper'` for multi-sketches apps. Besides this small change, you are good to go. The same applies if you use [p5js-vite](https://github.com/makinteract/p5js-vite).

I will close the issue. Thanks
